steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - helloworld
  - --region=us-central1
  - --source=./helloworld/
  - --trigger-http
  - --runtime=python39